name: Build DynamicOpenVR

on: [ push ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x

    - name: Set manifest version
      run: ./bsipa_version_hash.ps1 "Packaging\DynamicOpenVR\Plugins\DynamicOpenVR.manifest" "Source\DynamicOpenVR\Properties\AssemblyInfo.cs"

    - name: Build Debug
      run: dotnet build Source\DynamicOpenVR\DynamicOpenVR.csproj -c Debug

    - name: Upload Debug
      uses: actions/upload-artifact@v2.2.0
      with:
        name: DynamicOpenVR-${{ env.ZIP_VERSION }}-DEBUG
        path: Source\DynamicOpenVR\bin\Debug\net4.7.2\publish

    - name: Build Release
      run: dotnet build Source\DynamicOpenVR\DynamicOpenVR.csproj -c Release

    - name: Upload Release
      uses: actions/upload-artifact@v2.2.0
      with:
        name: DynamicOpenVR-${{ env.ZIP_VERSION }}-RELEASE
        path: Source\DynamicOpenVR\bin\Release\net4.7.2\publish