name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - Libraries/**
    - Packaging/**
    - Source/**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up environment
      run: ${{ github.workspace }}\.github\workflows\set_up_env.ps1 "${{ github.workspace }}\Packaging\DynamicOpenVR\Plugins\DynamicOpenVR.manifest"

    - name: Fetch Beat Saber Bindings
      run: git clone https://${{ github.actor }}:${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/nicoco007/BeatSaberBindings --branch v${{ env.GAME_VERSION }} --single-branch '${{ runner.temp }}\BeatSaberBindings\Beat Saber_Data\Managed'

    - name: Build Debug
      run: dotnet build Source\DynamicOpenVR\DynamicOpenVR.csproj -c Debug -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v3
      with:
        name: DynamicOpenVR-${{ env.ZIP_VERSION }}-DEBUG
        path: Source\DynamicOpenVR\bin\Debug\netstandard2.0\publish

    - name: Build Release
      run: dotnet build Source\DynamicOpenVR\DynamicOpenVR.csproj -c Release -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: DynamicOpenVR-${{ env.ZIP_VERSION }}-RELEASE
        path: Source\DynamicOpenVR\bin\Release\netstandard2.0\publish
