name: Build DynamicOpenVR.BeatSaber

on: [ push ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x

    - name: Fetch Beat Saber Bindings
      uses: actions/checkout@v2
      with:
        repository: nicoco007/BeatSaberBindings
        token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        path: BeatSaberBindings\Beat Saber_Data\Managed

    - name: Set manifest version
      run: ./bsipa_version_hash.ps1 "Source\DynamicOpenVR.BeatSaber\manifest.json" "Source\DynamicOpenVR.BeatSaber\Properties\AssemblyInfo.cs"

    - name: Build Debug
      run: dotnet build Source\DynamicOpenVR.BeatSaber\DynamicOpenVR.BeatSaber.csproj -c Debug -p:BeatSaberDir=..\..\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v2.2.0
      with:
        name: DynamicOpenVR.BeatSaber-${{ env.ZIP_VERSION }}-DEBUG
        path: Source\DynamicOpenVR.BeatSaber\bin\Debug\net4.7.2\publish

    - name: Build Release
      run: dotnet build Source\DynamicOpenVR.BeatSaber\DynamicOpenVR.BeatSaber.csproj -c Release -p:BeatSaberDir=..\..\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v2.2.0
      with:
        name: DynamicOpenVR.BeatSaber-${{ env.ZIP_VERSION }}-RELEASE
        path: Source\DynamicOpenVR.BeatSaber\bin\Release\net4.7.2\publish