name: Build (Beat Saber)

on:
  push:
    paths:
    - .github/workflows/build.yml
    - Libraries/**
    - Packaging/**
    - Source/**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up environment
      run: ${{ github.workspace }}\.github\workflows\set_up_env.ps1 "${{ github.workspace }}\Source\DynamicOpenVR.BeatSaber\manifest.json"

    - name: Fetch Beat Saber Bindings
      run: git clone https://${{ github.actor }}:${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/nicoco007/BeatSaberBindings --branch v${{ env.GAME_VERSION }} --single-branch '${{ runner.temp }}\BeatSaberBindings\Beat Saber_Data\Managed'

    - name: Add NuGet source
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text "https://nuget.pkg.github.com/nicoco007/index.json"

    - name: Download dependencies
      uses: nicoco007/download-beatmods-deps@main
      with:
        manifest: ${{ github.workspace }}\Source\DynamicOpenVR.BeatSaber\manifest.json
        path: ${{ runner.temp }}\BeatSaberBindings

    - name: Build Debug
      run: dotnet publish Source\DynamicOpenVR.BeatSaber\DynamicOpenVR.BeatSaber.csproj -c Debug -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v3
      with:
        name: DynamicOpenVR.BeatSaber-${{ env.ZIP_VERSION }}-DEBUG
        path: Source\DynamicOpenVR.BeatSaber\bin\Debug\net472\publish

    - name: Build Release
      run: dotnet publish Source\DynamicOpenVR.BeatSaber\DynamicOpenVR.BeatSaber.csproj -c Release -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: DynamicOpenVR.BeatSaber-${{ env.ZIP_VERSION }}-RELEASE
        path: Source\DynamicOpenVR.BeatSaber\bin\Release\net472\publish
